targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          named_parameters: true
          data_class_to_companions: true
          generate_manager: false
          write_to_columns_mixins: false
