"""Islamic quiz – original multiple-choice questions written for Madar.

Each question: (category, level, question_ar, question_en, options_ar,
options_en, sources). The FIRST option is the correct one (the build shuffles
options deterministically per question). Levels: 1 easy, 2 medium, 3 hard.

Sources (every question has at least one, and the build verifies each):
  Qr(sura, ayah, key)      the ayah exists and its letter skeleton contains
                           `key` (checked against the bundled Tanzil text,
                           assets/quran/quran-uthmani.txt – also re-checked by
                           the Dart tests);
  Hd(book, number, key)    the hadith with that number (Bukhari: standard
                           numbering; Muslim: Muhammad Fu'ad 'Abd al-Baqi;
                           Tirmidhi / Abu Dawud: standard) contains `key`
                           (checked at build time against fawazahmed0's
                           hadith editions);
  Mt(kind, **facts)        a fact of the mushaf's structure, checked against
                           the bundled Tanzil metadata (assets/quran/
                           quran-meta.json) and text.

Scope: Quran facts, prophets, seerah, the pillars, the companions and
manners – topics with clear consensus. No contested fiqh rulings.
"""


def Qr(s, a, key):
    return {'t': 'quran', 's': s, 'a': a, 'k': key}


def Hd(book, n, key):
    return {'t': 'hadith', 'b': book, 'n': n, 'k': key}


def Mt(kind, **facts):
    return {'t': 'meta', 'k': kind, **facts}


QUESTIONS = [
    # ===================================================================== quran
    ('quran', 1, 'كم عدد سور القرآن الكريم؟', 'How many surahs does the Quran have?',
     ['١١٤', '١١٠', '١٢٠', '٩٩'], ['114', '110', '120', '99'],
     [Mt('sura_count', v=114)]),
    ('quran', 1, 'ما أول سورة في ترتيب المصحف؟', 'Which surah comes first in the order of the mushaf?',
     ['الفاتحة', 'البقرة', 'العلق', 'الإخلاص'], ['Al-Fatihah', 'Al-Baqarah', "Al-'Alaq", 'Al-Ikhlas'],
     [Mt('sura_at', n=1, name='الفاتحة')]),
    ('quran', 1, 'ما آخر سورة في ترتيب المصحف؟', 'Which surah comes last in the order of the mushaf?',
     ['الناس', 'الفلق', 'الإخلاص', 'الكوثر'], ['An-Nas', 'Al-Falaq', 'Al-Ikhlas', 'Al-Kawthar'],
     [Mt('sura_at', n=114, name='الناس')]),
    ('quran', 1, 'ما أطول سورة في القرآن الكريم؟', 'Which is the longest surah of the Quran?',
     ['البقرة', 'آل عمران', 'النساء', 'الأعراف'], ['Al-Baqarah', "Ali 'Imran", 'An-Nisa', "Al-A'raf"],
     [Mt('longest_sura', n=2)]),
    ('quran', 1, 'ما السورة التي لا تبدأ بالبسملة؟', 'Which surah does not begin with the basmala?',
     ['التوبة', 'الأنفال', 'يونس', 'هود'], ['At-Tawbah', 'Al-Anfal', 'Yunus', 'Hud'],
     [Mt('no_basmala', n=9), Qr(9, 1, 'براءه من الله')]),
    ('quran', 2, 'في أي سورة وردت البسملة مرتين؟', 'In which surah does the basmala occur twice?',
     ['النمل', 'النحل', 'الفاتحة', 'التوبة'], ['An-Naml', 'An-Nahl', 'Al-Fatihah', 'At-Tawbah'],
     [Qr(27, 30, 'انه من سليمن وانه بسم الله الرحمن الرحيم')]),
    ('quran', 1, 'كم عدد آيات سورة الفاتحة؟', 'How many ayat does Surah Al-Fatihah have?',
     ['٧', '٥', '٦', '٩'], ['7', '5', '6', '9'],
     [Mt('ayah_count', n=1, v=7)]),
    ('quran', 1, 'في أي سورة تقع آية الكرسي؟', 'In which surah is Ayat al-Kursi?',
     ['البقرة', 'آل عمران', 'الكهف', 'يس'], ['Al-Baqarah', "Ali 'Imran", 'Al-Kahf', 'Ya-Sin'],
     [Qr(2, 255, 'وسع كرسيه السموت والارض')]),
    ('quran', 2, 'كم عدد آيات سورة البقرة؟', 'How many ayat does Surah Al-Baqarah have?',
     ['٢٨٦', '٢٠٠', '١٧٦', '٢٢٧'], ['286', '200', '176', '227'],
     [Mt('ayah_count', n=2, v=286)]),
    ('quran', 1, 'ما السورة التي تحمل اسم امرأة؟', 'Which surah is named after a woman?',
     ['مريم', 'النساء', 'المجادلة', 'الممتحنة'], ['Maryam', 'An-Nisa', 'Al-Mujadilah', 'Al-Mumtahanah'],
     [Mt('sura_at', n=19, name='مريم'), Qr(19, 16, 'واذكر في الكتب مريم')]),
    ('quran', 2, 'من المرأة التي ذُكر اسمها صراحة في القرآن الكريم؟', 'Which woman is mentioned by name in the Quran?',
     ['مريم ابنة عمران', 'خديجة بنت خويلد', 'آسية امرأة فرعون', 'هاجر أم إسماعيل'],
     ["Maryam, daughter of 'Imran", 'Khadijah bint Khuwaylid', "Asiya, Pharaoh's wife", 'Hajar, mother of Isma\'il'],
     [Qr(66, 12, 'ومريم ابنت عمرن')]),
    ('quran', 1, 'ما السورة التي تعدل ثلث القرآن؟', 'Which surah is equal to a third of the Quran?',
     ['الإخلاص', 'الفاتحة', 'الكوثر', 'الناس'], ['Al-Ikhlas', 'Al-Fatihah', 'Al-Kawthar', 'An-Nas'],
     [Hd('bukhari', 5013, 'لتعدل ثلث القران')]),
    ('quran', 1, 'ما أول ما نزل من القرآن الكريم؟', 'What were the first words of the Quran to be revealed?',
     ['اقرأ باسم ربك الذي خلق', 'الحمد لله رب العالمين', 'قل هو الله أحد', 'يا أيها المدثر'],
     ['"Read in the name of your Lord who created"', '"All praise is for Allah, Lord of the worlds"',
      '"Say: He is Allah, the One"', '"O you wrapped in your cloak"'],
     [Hd('bukhari', 3, 'اقرا باسم ربك الذي خلق'), Qr(96, 1, 'اقرا باسم ربك الذي خلق')]),
    ('quran', 1, 'في أي غار نزل الوحي على النبي ﷺ أول مرة؟', 'In which cave did the first revelation come to the Prophet ﷺ?',
     ['غار حراء', 'غار ثور', 'غار أحد', 'غار الكهف'], ['The cave of Hira', 'The cave of Thawr', 'A cave in Uhud', 'The cave of the Sleepers'],
     [Hd('bukhari', 3, 'يخلو بغار حراء')]),
    ('quran', 1, 'في أي شهر أُنزل القرآن الكريم؟', 'In which month was the Quran sent down?',
     ['رمضان', 'شعبان', 'رجب', 'ذو الحجة'], ['Ramadan', "Sha'ban", 'Rajab', 'Dhul-Hijjah'],
     [Qr(2, 185, 'شهر رمضان الذي انزل فيه القران')]),
    ('quran', 1, 'في أي ليلة أُنزل القرآن الكريم؟', 'In which night was the Quran sent down?',
     ['ليلة القدر', 'ليلة النصف من شعبان', 'ليلة الإسراء', 'ليلة عرفة'],
     ['Laylat al-Qadr', "The night of mid-Sha'ban", 'The night of the Isra', 'The night of Arafah'],
     [Qr(97, 1, 'انا انزلنه في ليله القدر')]),
    ('quran', 1, 'ليلة القدر خير من كم شهر؟', 'Laylat al-Qadr is better than how many months?',
     ['ألف شهر', 'مئة شهر', 'سبعين شهرًا', 'اثني عشر شهرًا'], ['A thousand months', 'A hundred months', 'Seventy months', 'Twelve months'],
     [Qr(97, 3, 'ليله القدر خير من الف شهر')]),
    ('quran', 1, 'بأي لغة أُنزل القرآن الكريم؟', 'In which language was the Quran revealed?',
     ['العربية', 'العبرية', 'السريانية', 'الفارسية'], ['Arabic', 'Hebrew', 'Syriac', 'Persian'],
     [Qr(12, 2, 'عربيا لعلكم تعقلون')]),
    ('quran', 1, 'ما السورة التي تبدأ بقوله تعالى: «قل هو الله أحد»؟', 'Which surah begins with "Say: He is Allah, the One"?',
     ['الإخلاص', 'الكافرون', 'الفلق', 'الناس'], ['Al-Ikhlas', 'Al-Kafirun', 'Al-Falaq', 'An-Nas'],
     [Qr(112, 1, 'قل هو الله احد'), Mt('sura_at', n=112, name='الإخلاص')]),
    ('quran', 1, 'ما السورة التي ذكرت أصحاب الفيل؟', 'Which surah mentions the People of the Elephant?',
     ['الفيل', 'قريش', 'البقرة', 'الماعون'], ['Al-Fil', 'Quraysh', 'Al-Baqarah', "Al-Ma'un"],
     [Qr(105, 1, 'باصحب الفيل')]),
    ('quran', 1, 'ما السورة التي تحمل اسم قبيلة النبي ﷺ؟', "Which surah is named after the Prophet's ﷺ tribe?",
     ['قريش', 'الأحزاب', 'الحجرات', 'سبأ'], ['Quraysh', 'Al-Ahzab', 'Al-Hujurat', 'Saba'],
     [Qr(106, 1, 'لايلف قريش')]),
    ('quran', 1, 'في أي سورة تتكرر آية «فبأي آلاء ربكما تكذبان»؟', 'In which surah is the ayah "Which of the favours of your Lord will you deny?" repeated?',
     ['الرحمن', 'الواقعة', 'القمر', 'الملك'], ['Ar-Rahman', "Al-Waqi'ah", 'Al-Qamar', 'Al-Mulk'],
     [Qr(55, 13, 'فباي الاء ربكما تكذبان')]),
    ('quran', 1, 'ما السورة التي تحمل اسم الحشرة التي تصنع العسل؟', 'Which surah is named after the insect that makes honey?',
     ['النحل', 'النمل', 'العنكبوت', 'الفيل'], ['An-Nahl (The Bee)', 'An-Naml (The Ant)', "Al-'Ankabut (The Spider)", 'Al-Fil (The Elephant)'],
     [Qr(16, 68, 'واوحي ربك الي النحل')]),
    ('quran', 1, 'في أي سورة قالت نملة: «ادخلوا مساكنكم»؟', 'In which surah did an ant say "Enter your dwellings"?',
     ['النمل', 'النحل', 'سبأ', 'البقرة'], ['An-Naml', 'An-Nahl', 'Saba', 'Al-Baqarah'],
     [Qr(27, 18, 'ادخلوا مسكنكم')]),
    ('quran', 2, 'ما البيت الذي وصفه القرآن بأنه أوهن البيوت؟', 'Which house does the Quran describe as the frailest of houses?',
     ['بيت العنكبوت', 'بيت النمل', 'بيت النحل', 'بيت الطير'], ["The spider's house", "The ant's nest", "The bees' hive", "The bird's nest"],
     [Qr(29, 41, 'وان اوهن البيوت لبيت العنكبوت')]),
    ('quran', 1, 'في أي سورة وردت قصة أصحاب الكهف؟', 'Which surah tells the story of the People of the Cave?',
     ['الكهف', 'مريم', 'يس', 'الأنبياء'], ['Al-Kahf', 'Maryam', 'Ya-Sin', "Al-Anbiya"],
     [Qr(18, 9, 'اصحب الكهف')]),
    ('quran', 2, 'كم سنة لبث أصحاب الكهف في كهفهم؟', 'How many years did the People of the Cave stay in their cave?',
     ['ثلاثمئة وتسع سنين', 'مئة سنة', 'أربعون سنة', 'ثلاثمئة سنة فقط'], ['309 years', '100 years', '40 years', 'Exactly 300 years'],
     [Qr(18, 25, 'ولبثوا في كهفهم')]),
    ('quran', 2, 'بمَ وصف القرآن الكريم قصة يوسف عليه السلام؟', 'How does the Quran describe the story of Yusuf?',
     ['أحسن القصص', 'أعجب القصص', 'أطول القصص', 'أول القصص'], ['The best of stories', 'The most wondrous of stories', 'The longest of stories', 'The first of stories'],
     [Qr(12, 3, 'نحن نقص عليك احسن القصص')]),
    ('quran', 1, 'ما السورة التي تبدأ بـ«إذا جاء نصر الله والفتح»؟', 'Which surah begins with "When the victory of Allah has come, and the conquest"?',
     ['النصر', 'الفتح', 'الكوثر', 'العصر'], ['An-Nasr', 'Al-Fath', 'Al-Kawthar', "Al-'Asr"],
     [Qr(110, 1, 'اذا جا نصر الله والفتح')]),
    ('quran', 1, 'في أي سورة ذُكرت رحلة الإسراء؟', 'Which surah mentions the Night Journey (al-Isra)?',
     ['الإسراء', 'النجم', 'الكهف', 'الفتح'], ['Al-Isra', 'An-Najm', 'Al-Kahf', 'Al-Fath'],
     [Qr(17, 1, 'سبحن الذي اسري بعبده')]),
    ('quran', 1, 'إلى أي مسجد أُسري بالنبي ﷺ من المسجد الحرام؟', 'To which mosque was the Prophet ﷺ taken by night from al-Masjid al-Haram?',
     ['المسجد الأقصى', 'المسجد النبوي', 'مسجد قباء', 'مسجد الخيف'],
     ['Al-Masjid al-Aqsa', "The Prophet's Mosque", "Quba' Mosque", 'Al-Khayf Mosque'],
     [Qr(17, 1, 'الي المسجد الاقصا')]),
    ('quran', 1, 'كم عدد آيات سورة الكوثر؟', 'How many ayat does Surah Al-Kawthar have?',
     ['٣', '٤', '٥', '٧'], ['3', '4', '5', '7'],
     [Mt('ayah_count', n=108, v=3)]),
    ('quran', 2, 'أي هذه السور عدد آياتها ثلاث؟', 'Which of these surahs has three ayat?',
     ['العصر', 'الإخلاص', 'الفلق', 'الناس'], ["Al-'Asr", 'Al-Ikhlas', 'Al-Falaq', 'An-Nas'],
     [Mt('ayah_count', n=103, v=3), Mt('ayah_count', n=112, v=4), Mt('ayah_count', n=113, v=5), Mt('ayah_count', n=114, v=6)]),
    ('quran', 1, 'كم عدد آيات سورة الإخلاص؟', 'How many ayat does Surah Al-Ikhlas have?',
     ['٤', '٣', '٥', '٦'], ['4', '3', '5', '6'],
     [Mt('ayah_count', n=112, v=4)]),
    ('quran', 1, 'كم عدد أجزاء القرآن الكريم؟', 'Into how many juz is the Quran divided?',
     ['٣٠', '٦٠', '٢٠', '١١٤'], ['30', '60', '20', '114'],
     [Mt('juz_count', v=30)]),
    ('quran', 2, 'بأي سورة يبدأ الجزء الثلاثون (جزء عمّ)؟', 'Which surah opens the thirtieth juz (Juz \'Amma)?',
     ['النبأ', 'الملك', 'الأعلى', 'الفجر'], ["An-Naba'", 'Al-Mulk', "Al-A'la", 'Al-Fajr'],
     [Mt('juz_start', n=30, sura=78, ayah=1)]),
    ('quran', 2, 'كم عدد صفحات المصحف الشريف في طبعة المدينة المنورة المعتادة؟', 'How many pages does the standard Madinah mushaf have?',
     ['٦٠٤', '٥٠٠', '٦٣٠', '٤٤٤'], ['604', '500', '630', '444'],
     [Mt('page_count', v=604)]),
    ('quran', 2, 'أي السور التالية سُمّيت باسم نبي؟', 'Which of these surahs is named after a prophet?',
     ['يونس', 'الكهف', 'الحديد', 'النور'], ['Yunus', 'Al-Kahf', 'Al-Hadid', 'An-Nur'],
     [Mt('sura_at', n=10, name='يونس'), Qr(10, 98, 'قوم يونس')]),
    ('quran', 2, 'ما ترتيب سورة يس في المصحف؟', 'What is the number of Surah Ya-Sin in the mushaf?',
     ['٣٦', '١٨', '٥٥', '٦٧'], ['36', '18', '55', '67'],
     [Mt('sura_at', n=36, name='يس')]),
    ('quran', 2, 'ما ترتيب سورة الكهف في المصحف؟', 'What is the number of Surah Al-Kahf in the mushaf?',
     ['١٨', '١٩', '١٧', '٢٠'], ['18', '19', '17', '20'],
     [Mt('sura_at', n=18, name='الكهف')]),
    ('quran', 2, 'ما السورة التي تبدأ بـ«تبارك الذي بيده الملك»؟', 'Which surah begins with "Blessed is He in whose hand is the dominion"?',
     ['الملك', 'الفرقان', 'القلم', 'المؤمنون'], ['Al-Mulk', 'Al-Furqan', 'Al-Qalam', "Al-Mu'minun"],
     [Qr(67, 1, 'بيده الملك')]),
    ('quran', 1, 'كم عدد آيات سورة الملك؟', 'How many ayat does Surah Al-Mulk have?',
     ['٣٠', '٢٩', '٤٠', '٢٥'], ['30', '29', '40', '25'],
     [Mt('ayah_count', n=67, v=30)]),
    ('quran', 2, 'من الصحابي الوحيد الذي ذُكر اسمه في القرآن الكريم؟', 'Which companion is the only one mentioned by name in the Quran?',
     ['زيد بن حارثة', 'أبو بكر الصديق', 'عمر بن الخطاب', 'بلال بن رباح'], ['Zayd ibn Harithah', 'Abu Bakr as-Siddiq', 'Umar ibn al-Khattab', 'Bilal ibn Rabah'],
     [Qr(33, 37, 'فلما قضي زيد منها وطرا')]),
    ('quran', 1, 'من الذي نزلت فيه سورة المسد وذُكر اسمه فيها؟', 'Who is named in Surah Al-Masad?',
     ['أبو لهب', 'أبو جهل', 'أبو طالب', 'الوليد بن المغيرة'], ['Abu Lahab', 'Abu Jahl', 'Abu Talib', 'Al-Walid ibn al-Mughirah'],
     [Qr(111, 1, 'تبت يدا ابي لهب')]),
    ('quran', 2, 'كم مرة ورد اسم «محمد» ﷺ في القرآن الكريم؟', 'How many times is the name "Muhammad" ﷺ mentioned in the Quran?',
     ['٤ مرات', 'مرتان', '٧ مرات', '١٠ مرات'], ['4 times', 'Twice', '7 times', '10 times'],
     [Qr(3, 144, 'وما محمد الا رسول'), Qr(33, 40, 'ما كان محمد ابا احد'), Qr(47, 2, 'بما نزل علي محمد'),
      Qr(48, 29, 'محمد رسول الله'), Mt('ayat_containing', key='محمد', v=4)]),
    ('quran', 2, 'بأي اسم بشّر عيسى عليه السلام بالنبي ﷺ؟', 'By which name did \'Isa give glad tidings of the Prophet ﷺ?',
     ['أحمد', 'محمود', 'حامد', 'مصطفى'], ['Ahmad', 'Mahmud', 'Hamid', 'Mustafa'],
     [Qr(61, 6, 'ومبشرا برسول ياتي من بعدي اسمه احمد')]),
    ('quran', 2, 'أي الأنبياء ذُكر اسمه في أكبر عدد من آيات القرآن الكريم؟', 'Which prophet is named in the largest number of ayat?',
     ['موسى', 'إبراهيم', 'نوح', 'عيسى'], ['Musa', 'Ibrahim', 'Nuh', "'Isa"],
     [Mt('most_named', names=['موسي', 'ابرهيم', 'نوح', 'عيسي'], v='موسي')]),
    ('quran', 3, 'أطول آية في القرآن الكريم هي آية الدَّين، ففي أي سورة هي؟', 'The longest ayah of the Quran is the ayah of debt. In which surah is it?',
     ['البقرة', 'النساء', 'آل عمران', 'المائدة'], ['Al-Baqarah', 'An-Nisa', "Ali 'Imran", "Al-Ma'idah"],
     [Mt('longest_ayah', s=2, a=282), Qr(2, 282, 'اذا تداينتم بدين')]),
    ('quran', 1, 'بمَ وصف القرآنُ نفسَه في أول سورة البقرة؟', 'How does the Quran describe itself at the start of Surah Al-Baqarah?',
     ['هدى للمتقين', 'شفاء للناس', 'نورًا للعالمين', 'ذكرى للمؤمنين'], ['Guidance for the God-conscious', 'A cure for people', 'A light for the worlds', 'A reminder for believers'],
     [Qr(2, 2, 'ذلك الكتب لا ريب فيه هدي للمتقين')]),
    ('quran', 2, 'في أي سورة جاء قوله تعالى: «إنا نحن نزلنا الذكر وإنا له لحافظون»؟', 'In which surah is "Indeed, We sent down the Reminder and We will surely guard it"?',
     ['الحجر', 'الحج', 'النحل', 'يونس'], ['Al-Hijr', 'Al-Hajj', 'An-Nahl', 'Yunus'],
     [Qr(15, 9, 'انا نحن نزلنا الذكر وانا له لحفظون')]),
    ('quran', 2, 'بماذا تحدّى القرآن الكريم المكذبين في سورة البقرة؟', 'What did the Quran challenge the deniers to produce in Surah Al-Baqarah?',
     ['أن يأتوا بسورة من مثله', 'أن يأتوا بكتاب أطول', 'أن يأتوا بآية من السماء', 'أن يأتوا بشعر مثله'],
     ['A surah like it', 'A longer book', 'A sign from the sky', 'Poetry like it'],
     [Qr(2, 23, 'فاتوا بسوره من مثله')]),
    ('quran', 1, 'ما السورة التي تبدأ بـ«يا أيها المدثر»؟', 'Which surah begins with "O you wrapped in your cloak (al-Muddaththir)"?',
     ['المدثر', 'المزمل', 'العلق', 'الضحى'], ['Al-Muddaththir', 'Al-Muzzammil', "Al-'Alaq", 'Ad-Duha'],
     [Qr(74, 1, 'يايها المدثر')]),
    ('quran', 1, 'في أي سورة أقسم الله بالعصر أن الإنسان لفي خسر؟', 'In which surah does Allah swear by time that mankind is in loss?',
     ['العصر', 'الضحى', 'الليل', 'الفجر'], ["Al-'Asr", 'Ad-Duha', 'Al-Layl', 'Al-Fajr'],
     [Qr(103, 2, 'ان الانسن لفي خسر')]),
    ('quran', 2, 'في أي سورة ذُكرت «إرم ذات العماد»؟', 'Which surah mentions "Iram of the pillars"?',
     ['الفجر', 'الأحقاف', 'هود', 'الشعراء'], ['Al-Fajr', 'Al-Ahqaf', 'Hud', "Ash-Shu'ara"],
     [Qr(89, 7, 'ارم ذات العماد')]),
    ('quran', 1, 'بأي فاكهتين أقسم الله في أول سورة التين؟', 'By which two fruits does Allah swear at the start of Surah At-Tin?',
     ['التين والزيتون', 'العنب والنخل', 'الرمان والتين', 'الزيتون والرمان'], ['Figs and olives', 'Grapes and date palms', 'Pomegranates and figs', 'Olives and pomegranates'],
     [Qr(95, 1, 'والتين والزيتون')]),
    ('quran', 2, 'ما الاسم الذي ورد لمكة في قوله تعالى: «إن أول بيت وُضع للناس للذي ...»؟', 'Which name of Makkah appears in "The first House established for mankind is the one at ..."?',
     ['بكة', 'يثرب', 'أم القرى فقط', 'طيبة'], ['Bakkah', 'Yathrib', 'Umm al-Qura', 'Taybah'],
     [Qr(3, 96, 'ان اول بيت وضع للناس للذي ببكه')]),
    ('quran', 2, 'أي مدينة ورد ذكرها في القرآن باسم «يثرب»؟', 'Which city is mentioned in the Quran by the name "Yathrib"?',
     ['المدينة المنورة', 'مكة المكرمة', 'الطائف', 'خيبر'], ['Madinah', 'Makkah', "Ta'if", 'Khaybar'],
     [Qr(33, 13, 'يثرب')]),
    ('quran', 2, 'في أي سورة أخبر القرآن بهزيمة الروم ثم غلبتهم؟', 'Which surah foretold the defeat of the Romans and their later victory?',
     ['الروم', 'الفيل', 'سبأ', 'الفتح'], ['Ar-Rum', 'Al-Fil', 'Saba', 'Al-Fath'],
     [Qr(30, 2, 'غلبت الروم')]),
    ('quran', 1, 'ما السورة التي تبدأ بـ«قد أفلح المؤمنون»؟', 'Which surah begins with "Successful indeed are the believers"?',
     ['المؤمنون', 'المؤمن (غافر)', 'الحج', 'النور'], ["Al-Mu'minun", "Ghafir (Al-Mu'min)", 'Al-Hajj', 'An-Nur'],
     [Qr(23, 1, 'قد افلح المومنون')]),
    ('quran', 1, 'بمَ بدأ لقمان وصيته لابنه في القرآن الكريم؟', 'With what did Luqman begin his advice to his son?',
     ['لا تشرك بالله', 'أقم الصلاة', 'لا تمش في الأرض مرحًا', 'اقصد في مشيك'],
     ['Do not associate anything with Allah', 'Establish prayer', 'Do not walk arrogantly', 'Be moderate in your pace'],
     [Qr(31, 13, 'يبني لا تشرك بالله')]),
    ('quran', 2, 'كم عدد آيات سورة يوسف؟', 'How many ayat does Surah Yusuf have?',
     ['١١١', '١١٠', '١٢٣', '٩٩'], ['111', '110', '123', '99'],
     [Mt('ayah_count', n=12, v=111)]),
    ('quran', 1, 'بحسب سورة الحجرات، من أكرم الناس عند الله؟', 'According to Surah Al-Hujurat, who is the most noble in the sight of Allah?',
     ['أتقاهم', 'أغناهم', 'أقواهم', 'أكبرهم سنًّا'], ['The most God-conscious', 'The richest', 'The strongest', 'The oldest'],
     [Qr(49, 13, 'ان اكرمكم عند الله اتقيكم')]),
    ('quran', 2, 'في أي سورة وردت آية «لا إكراه في الدين»؟', 'Which surah contains "There is no compulsion in religion"?',
     ['البقرة', 'الكافرون', 'يونس', 'الأنعام'], ['Al-Baqarah', 'Al-Kafirun', 'Yunus', "Al-An'am"],
     [Qr(2, 256, 'لا اكراه في الدين')]),
    ('quran', 2, 'في أي سورة وردت قصة ذي القرنين؟', 'Which surah tells the story of Dhul-Qarnayn?',
     ['الكهف', 'الأنبياء', 'طه', 'الحج'], ['Al-Kahf', "Al-Anbiya", 'Ta-Ha', 'Al-Hajj'],
     [Qr(18, 83, 'ويسلونك عن ذي القرنين')]),
    ('quran', 3, 'ممَّ صنع ذو القرنين الردم أمام يأجوج ومأجوج؟', 'What did Dhul-Qarnayn use to build the barrier against Ya\'juj and Ma\'juj?',
     ['قطع الحديد والنحاس المذاب', 'الحجارة والطين', 'الخشب والقار', 'الذهب والفضة'],
     ['Blocks of iron and molten copper', 'Stones and clay', 'Wood and tar', 'Gold and silver'],
     [Qr(18, 96, 'اتوني زبر الحديد'), Qr(18, 96, 'افرغ عليه قطرا')]),
    ('quran', 2, 'ماذا كان يفعل كلب أصحاب الكهف كما وصفه القرآن؟', 'How does the Quran describe the dog of the People of the Cave?',
     ['باسط ذراعيه بالوصيد', 'نائم في داخل الكهف', 'يحرسهم واقفًا على الجبل', 'يأتيهم بالطعام'],
     ['Stretching its forelegs at the entrance', 'Sleeping deep inside the cave', 'Standing guard on the mountain', 'Bringing them food'],
     [Qr(18, 18, 'وكلبهم بسط ذراعيه بالوصيد')]),
    ('quran', 3, 'أين كان موعد موسى عليه السلام مع العبد الصالح كما في سورة الكهف؟', "Where was Musa's meeting place with the righteous servant in Surah Al-Kahf?",
     ['مجمع البحرين', 'جبل الطور', 'ساحل البحر الأحمر', 'مدين'], ['The junction of the two seas', 'Mount Tur', 'The Red Sea coast', 'Madyan'],
     [Qr(18, 60, 'حتي ابلغ مجمع البحرين')]),
    ('quran', 2, 'كم ليلة كان ميقات موسى عليه السلام مع ربه بعد إتمامه؟', "How many nights did Musa's appointed time with his Lord last in total?",
     ['أربعين ليلة', 'ثلاثين ليلة', 'عشر ليال', 'سبعين ليلة'], ['Forty nights', 'Thirty nights', 'Ten nights', 'Seventy nights'],
     [Qr(7, 142, 'فتم ميقت ربه اربعين ليله')]),
    ('quran', 2, 'كم لبث نوح عليه السلام في قومه يدعوهم؟', 'How long did Nuh remain among his people calling them?',
     ['ألف سنة إلا خمسين عامًا', 'مئة عام', 'خمسمئة عام', 'ألف عام كاملة'], ['A thousand years less fifty', 'A hundred years', 'Five hundred years', 'A full thousand years'],
     [Qr(29, 14, 'فلبث فيهم الف سنه الا خمسين عاما')]),
    ('quran', 1, 'كم كوكبًا رأى يوسف عليه السلام في منامه؟', 'How many stars did Yusuf see in his dream?',
     ['أحد عشر كوكبًا', 'سبعة كواكب', 'اثني عشر كوكبًا', 'عشرة كواكب'], ['Eleven', 'Seven', 'Twelve', 'Ten'],
     [Qr(12, 4, 'احد عشر كوكبا')]),
    ('quran', 3, 'كم عدد خزنة سقر كما في سورة المدثر؟', 'How many keepers are over Saqar according to Surah Al-Muddaththir?',
     ['تسعة عشر', 'سبعة', 'اثنا عشر', 'أربعون'], ['Nineteen', 'Seven', 'Twelve', 'Forty'],
     [Qr(74, 30, 'عليها تسعه عشر')]),
    ('quran', 3, 'كم يحمل عرشَ ربك يوم القيامة كما في سورة الحاقة؟', 'How many will bear the Throne on that Day according to Surah Al-Haqqah?',
     ['ثمانية', 'أربعة', 'سبعة', 'عشرة'], ['Eight', 'Four', 'Seven', 'Ten'],
     [Qr(69, 17, 'ويحمل عرش ربك فوقهم يوميذ ثمنيه')]),
    ('quran', 1, 'في كم يوم خلق الله السماوات والأرض كما ورد في القرآن؟', 'In how many days did Allah create the heavens and the earth according to the Quran?',
     ['ستة أيام', 'سبعة أيام', 'يومين', 'أربعة أيام'], ['Six days', 'Seven days', 'Two days', 'Four days'],
     [Qr(7, 54, 'خلق السموت والارض في سته ايام')]),
    ('quran', 1, 'كم عدد السماوات التي ذكرها القرآن الكريم؟', 'How many heavens does the Quran mention?',
     ['سبع', 'ثلاث', 'تسع', 'خمس'], ['Seven', 'Three', 'Nine', 'Five'],
     [Qr(67, 3, 'الذي خلق سبع سموت طباقا')]),
    ('quran', 1, 'كم عدد الشهور عند الله كما في سورة التوبة؟', 'How many months are there with Allah according to Surah At-Tawbah?',
     ['اثنا عشر شهرًا', 'عشرة أشهر', 'ثلاثة عشر شهرًا', 'أحد عشر شهرًا'], ['Twelve', 'Ten', 'Thirteen', 'Eleven'],
     [Qr(9, 36, 'ان عده الشهور عند الله اثنا عشر شهرا')]),
    ('quran', 1, 'كم عدد الأشهر الحُرُم؟', 'How many sacred months are there?',
     ['أربعة', 'ثلاثة', 'ستة', 'اثنان'], ['Four', 'Three', 'Six', 'Two'],
     [Qr(9, 36, 'منها اربعه حرم')]),
    ('quran', 1, 'ما الشهر الوحيد الذي ذُكر اسمه في القرآن الكريم؟', 'Which is the only month mentioned by name in the Quran?',
     ['رمضان', 'محرم', 'ذو الحجة', 'رجب'], ['Ramadan', 'Muharram', 'Dhul-Hijjah', 'Rajab'],
     [Qr(2, 185, 'شهر رمضان')]),
    ('quran', 2, 'كم عينًا انفجرت حين ضرب موسى الحجر بعصاه؟', 'How many springs gushed forth when Musa struck the rock with his staff?',
     ['اثنتا عشرة عينًا', 'سبع عيون', 'عشر عيون', 'عين واحدة'], ['Twelve', 'Seven', 'Ten', 'One'],
     [Qr(2, 60, 'فانفجرت منه اثنتا عشره عينا')]),
    ('quran', 2, 'ما الطعام الذي أنزله الله على بني إسرائيل في التيه؟', 'What food did Allah send down to the Children of Israel in the wilderness?',
     ['المنّ والسلوى', 'التمر واللبن', 'الخبز والعسل', 'السمك والرطب'], ['Manna and quails', 'Dates and milk', 'Bread and honey', 'Fish and fresh dates'],
     [Qr(2, 57, 'وانزلنا عليكم المن والسلوي')]),
    ('quran', 1, 'أي يوم أمر الله بالسعي إلى ذكره فيه إذا نودي للصلاة؟', 'On which day are believers told to hasten to the remembrance of Allah when called to prayer?',
     ['يوم الجمعة', 'يوم العيد', 'يوم عرفة', 'يوم الاثنين'], ['Friday', 'The day of Eid', 'The day of Arafah', 'Monday'],
     [Qr(62, 9, 'اذا نودي للصلوه من يوم الجمعه')]),
    ('quran', 2, 'ما السورة التي لا تصح الصلاة بدون قراءتها؟', 'Which surah must be recited for the prayer to be valid?',
     ['الفاتحة', 'الإخلاص', 'البقرة', 'الكوثر'], ['Al-Fatihah', 'Al-Ikhlas', 'Al-Baqarah', 'Al-Kawthar'],
     [Hd('bukhari', 756, 'لا صلاه لمن لم يقرا بفاتحه الكتاب')]),
    ('quran', 2, 'ما الاسم الذي وُصف به القرآن في أول سورة الفرقان؟', 'By what name is the Quran called at the start of Surah Al-Furqan?',
     ['الفرقان', 'الذكر', 'البرهان', 'الميزان'], ['Al-Furqan (the Criterion)', 'Adh-Dhikr', 'Al-Burhan', 'Al-Mizan'],
     [Qr(25, 1, 'نزل الفرقان علي عبده')]),
    ('quran', 1, 'في أي مدينة نزلت سورة البقرة؟', 'Where was Surah Al-Baqarah revealed?',
     ['المدينة', 'مكة', 'الطائف', 'القدس'], ['Madinah', 'Makkah', "Ta'if", 'Jerusalem'],
     [Mt('place', n=2, v='D')]),
    ('quran', 2, 'أي هذه السور مدنية؟', 'Which of these surahs is Madani?',
     ['النور', 'يوسف', 'مريم', 'الكهف'], ['An-Nur', 'Yusuf', 'Maryam', 'Al-Kahf'],
     [Mt('place', n=24, v='D'), Mt('place', n=12, v='M'), Mt('place', n=19, v='M'), Mt('place', n=18, v='M')]),
    ('quran', 2, 'أي هذه السور مكية؟', 'Which of these surahs is Makki?',
     ['الأنعام', 'البقرة', 'آل عمران', 'النساء'], ["Al-An'am", 'Al-Baqarah', "Ali 'Imran", 'An-Nisa'],
     [Mt('place', n=6, v='M'), Mt('place', n=2, v='D'), Mt('place', n=3, v='D'), Mt('place', n=4, v='D')]),
    ('quran', 2, 'ما السورة التي نزلت أولًا بحسب ترتيب النزول؟', 'Which surah was revealed first in the order of revelation?',
     ['العلق', 'الفاتحة', 'المدثر', 'البقرة'], ["Al-'Alaq", 'Al-Fatihah', 'Al-Muddaththir', 'Al-Baqarah'],
     [Mt('revealed_first', n=96)]),
    ('quran', 2, 'كم عدد آيات سورة الرحمن؟', 'How many ayat does Surah Ar-Rahman have?',
     ['٧٨', '٦٠', '٩٦', '٥٢'], ['78', '60', '96', '52'],
     [Mt('ayah_count', n=55, v=78)]),
    ('quran', 2, 'كم عدد آيات سورة آل عمران؟', "How many ayat does Surah Ali 'Imran have?",
     ['٢٠٠', '١٧٦', '١٢٠', '٢٨٦'], ['200', '176', '120', '286'],
     [Mt('ayah_count', n=3, v=200)]),
    ('quran', 3, 'كم عدد آيات سورة الكهف؟', 'How many ayat does Surah Al-Kahf have?',
     ['١١٠', '١١١', '٩٨', '١٣٥'], ['110', '111', '98', '135'],
     [Mt('ayah_count', n=18, v=110)]),
    ('quran', 2, 'ما السورة التي سُمّيت باسم معدن؟', 'Which surah is named after a metal?',
     ['الحديد', 'الذاريات', 'الطور', 'الحجر'], ['Al-Hadid (Iron)', 'Adh-Dhariyat', 'At-Tur', 'Al-Hijr'],
     [Mt('sura_at', n=57, name='الحديد'), Qr(57, 25, 'وانزلنا الحديد')]),
    ('quran', 1, 'ما السورة التي افتُتحت بـ«الحمد لله رب العالمين»؟', 'Which surah opens with "All praise is for Allah, Lord of the worlds"?',
     ['الفاتحة', 'الأنعام', 'الكهف', 'فاطر'], ['Al-Fatihah', "Al-An'am", 'Al-Kahf', 'Fatir'],
     [Qr(1, 2, 'الحمد لله رب العلمين')]),
    ('quran', 2, 'ما آخر كلمة في سورة الفاتحة؟', 'What is the last word of Surah Al-Fatihah?',
     ['الضالين', 'المستقيم', 'العالمين', 'الدين'], ["Ad-Dallin", 'Al-Mustaqim', "Al-'Alamin", 'Ad-Din'],
     [Qr(1, 7, 'ولا الضالين')]),
    ('quran', 2, 'بمَ وصف الله النبي ﷺ في سورة القلم؟', 'How does Allah describe the Prophet ﷺ in Surah Al-Qalam?',
     ['وإنك لعلى خلق عظيم', 'وإنك لمن المرسلين', 'رحمة للعالمين', 'خاتم النبيين'],
     ['"Indeed you are of a great moral character"', '"You are among the messengers"', '"A mercy to the worlds"', '"The seal of the prophets"'],
     [Qr(68, 4, 'وانك لعلي خلق عظيم')]),
    ('quran', 1, 'لمن أرسل الله نبيه محمدًا ﷺ رحمةً كما في سورة الأنبياء؟', 'According to Surah Al-Anbiya, the Prophet ﷺ was sent as a mercy to whom?',
     ['للعالمين', 'للعرب فقط', 'لقريش', 'للمؤمنين فقط'], ['The worlds', 'The Arabs only', 'Quraysh', 'The believers only'],
     [Qr(21, 107, 'وما ارسلنك الا رحمه للعلمين')]),
    ('quran', 2, 'بمَ وُصف النبي ﷺ في سورة الأحزاب بالنسبة إلى الأنبياء؟', 'How is the Prophet ﷺ described in relation to the prophets in Surah Al-Ahzab?',
     ['خاتم النبيين', 'أول النبيين', 'أكبر النبيين سنًّا', 'رسول بني إسرائيل'], ['The seal of the prophets', 'The first of the prophets', 'The oldest of the prophets', 'A messenger to the Children of Israel'],
     [Qr(33, 40, 'وخاتم النبين')]),
    ('quran', 3, 'في أي سورة ورد ذكر «مكة» بهذا الاسم؟', 'In which surah is Makkah mentioned by the name "Makkah"?',
     ['الفتح', 'البقرة', 'إبراهيم', 'البلد'], ['Al-Fath', 'Al-Baqarah', 'Ibrahim', 'Al-Balad'],
     [Qr(48, 24, 'ببطن مكه')]),
    ('quran', 2, 'في أي سورة وردت قصة البقرة التي أُمر بنو إسرائيل بذبحها؟', 'Which surah tells of the cow the Children of Israel were commanded to slaughter?',
     ['البقرة', 'الأعراف', 'طه', 'المائدة'], ['Al-Baqarah', "Al-A'raf", 'Ta-Ha', "Al-Ma'idah"],
     [Qr(2, 67, 'ان الله يامركم ان تذبحوا بقره')]),
    ('quran', 2, 'ما السورة التي تسمى «سورة بني إسرائيل» أيضًا؟', 'Which surah is also known as "Surah Bani Isra\'il"?',
     ['الإسراء', 'البقرة', 'طه', 'القصص'], ['Al-Isra', 'Al-Baqarah', 'Ta-Ha', 'Al-Qasas'],
     [Hd('bukhari', 4708, 'بني اسراييل والكهف ومريم'), Qr(17, 4, 'وقضينا الي بني اسريل')]),
    ('quran', 1, 'أي هذه السور تبدأ بـ«قل»؟', 'Which of these surahs begins with "Say (Qul)"?',
     ['الفلق', 'الفيل', 'الكوثر', 'العصر'], ['Al-Falaq', 'Al-Fil', 'Al-Kawthar', "Al-'Asr"],
     [Qr(113, 1, 'قل اعوذ برب الفلق')]),
    ('quran', 1, 'ما السورة التي تبدأ بـ«قل أعوذ برب الناس»؟', 'Which surah begins with "Say: I seek refuge in the Lord of mankind"?',
     ['الناس', 'الفلق', 'الإخلاص', 'الكافرون'], ['An-Nas', 'Al-Falaq', 'Al-Ikhlas', 'Al-Kafirun'],
     [Qr(114, 1, 'قل اعوذ برب الناس')]),
    ('quran', 2, 'ما السورة التي تبدأ بـ«طه»؟', 'Which surah begins with the letters "Ta-Ha"?',
     ['طه', 'يس', 'ص', 'ق'], ['Ta-Ha', 'Ya-Sin', 'Sad', 'Qaf'],
     [Mt('sura_at', n=20, name='طه')]),
    ('quran', 2, 'ما السورة التي تبدأ بـ«الم» وهي ثانية سور المصحف؟', 'Which surah begins with "Alif-Lam-Mim" and is the second in the mushaf?',
     ['البقرة', 'آل عمران', 'العنكبوت', 'الروم'], ['Al-Baqarah', "Ali 'Imran", "Al-'Ankabut", 'Ar-Rum'],
     [Mt('sura_at', n=2, name='البقرة'), Qr(2, 1, 'الم')]),
    ('quran', 2, 'ما أعظم آية في كتاب الله؟', 'What is the greatest ayah in the Book of Allah?',
     ['آية الكرسي', 'آية الدين', 'آخر آية في البقرة', 'أول آية في الفاتحة'], ['Ayat al-Kursi', 'The ayah of debt', 'The last ayah of Al-Baqarah', 'The first ayah of Al-Fatihah'],
     [Hd('muslim', 810, 'الله لا اله الا هو الحي القيوم'), Hd('muslim', 810, 'اعظم')]),
    ('quran', 2, 'في أي سورة وردت «آية النور»: «الله نور السماوات والأرض»؟', 'Which surah contains "Allah is the Light of the heavens and the earth"?',
     ['النور', 'الأنعام', 'الزمر', 'الحديد'], ['An-Nur', "Al-An'am", 'Az-Zumar', 'Al-Hadid'],
     [Qr(24, 35, 'الله نور السموت والارض')]),
    ('quran', 2, 'في أي سورة قال الله تعالى: «وجعلنا من الماء كل شيء حي»؟', 'Which surah says "We made from water every living thing"?',
     ['الأنبياء', 'النور', 'الفرقان', 'الملك'], ["Al-Anbiya", 'An-Nur', 'Al-Furqan', 'Al-Mulk'],
     [Qr(21, 30, 'وجعلنا من الما كل شي حي')]),
    # ================================================================= prophets
    ('prophets', 1, 'من أبو البشر؟', 'Who is the father of mankind?',
     ['آدم', 'نوح', 'إبراهيم', 'إدريس'], ['Adam', 'Nuh', 'Ibrahim', 'Idris'],
     [Qr(2, 31, 'وعلم ادم الاسما كلها')]),
    ('prophets', 1, 'ماذا علّم الله آدم عليه السلام كما في سورة البقرة؟', 'What did Allah teach Adam according to Surah Al-Baqarah?',
     ['الأسماء كلها', 'الكتابة بالقلم', 'صناعة الدروع', 'الزراعة'], ['The names, all of them', 'Writing with the pen', 'Making armour', 'Farming'],
     [Qr(2, 31, 'وعلم ادم الاسما كلها')]),
    ('prophets', 1, 'من الذي أبى أن يسجد لآدم عليه السلام؟', 'Who refused to prostrate to Adam?',
     ['إبليس', 'قابيل', 'هاروت', 'السامري'], ['Iblis', 'Qabil', 'Harut', 'As-Samiri'],
     [Qr(2, 34, 'فسجدوا الا ابليس ابي')]),
    ('prophets', 2, 'ماذا قال آدم وزوجه بعد أن أكلا من الشجرة؟', 'What did Adam and his wife say after eating from the tree?',
     ['ربنا ظلمنا أنفسنا', 'ربنا آتنا في الدنيا حسنة', 'رب اشرح لي صدري', 'حسبنا الله ونعم الوكيل'],
     ['"Our Lord, we have wronged ourselves"', '"Our Lord, give us good in this world"', '"My Lord, expand my chest"', '"Allah is sufficient for us"'],
     [Qr(7, 23, 'قالا ربنا ظلمنا انفسنا')]),
    ('prophets', 2, 'ماذا قرّب ابنا آدم كما في سورة المائدة؟', "What did Adam's two sons each offer, according to Surah Al-Ma'idah?",
     ['قربانًا', 'بيتًا', 'مالًا', 'شعرًا'], ['A sacrifice', 'A house', 'Money', 'A poem'],
     [Qr(5, 27, 'اذ قربا قربانا')]),
    ('prophets', 1, 'أي طائر بعثه الله ليُري ابن آدم كيف يواري أخاه؟', "Which bird did Allah send to show Adam's son how to bury his brother?",
     ['الغراب', 'الهدهد', 'الحمام', 'النسر'], ['A crow', 'A hoopoe', 'A dove', 'An eagle'],
     [Qr(5, 31, 'فبعث الله غرابا')]),
    ('prophets', 1, 'أي نبي صنع السفينة بأمر الله؟', 'Which prophet built the Ark by the command of Allah?',
     ['نوح', 'موسى', 'يونس', 'إبراهيم'], ['Nuh', 'Musa', 'Yunus', 'Ibrahim'],
     [Qr(11, 38, 'ويصنع الفلك')]),
    ('prophets', 2, 'على أي جبل استوت سفينة نوح عليه السلام؟', "On which mountain did Nuh's Ark come to rest?",
     ['الجودي', 'الطور', 'أحد', 'عرفات'], ['Al-Judi', 'At-Tur (Sinai)', 'Uhud', 'Arafat'],
     [Qr(11, 44, 'واستوت علي الجودي')]),
    ('prophets', 2, 'ماذا قال ابن نوح حين دعاه أبوه إلى ركوب السفينة؟', "What did Nuh's son say when his father called him to board the Ark?",
     ['سآوي إلى جبل يعصمني من الماء', 'سأركب بعد قليل', 'سأسبح إلى الشاطئ', 'سأبني سفينة أخرى'],
     ['"I will take refuge on a mountain to protect me from the water"', '"I will board shortly"', '"I will swim to the shore"', '"I will build another ship"'],
     [Qr(11, 43, 'ساوي الي جبل يعصمني من الما')]),
    ('prophets', 2, 'أي نبي دعا: «رب لا تذر على الأرض من الكافرين ديارًا»؟', 'Which prophet prayed: "My Lord, do not leave upon the earth any of the disbelievers"?',
     ['نوح', 'هود', 'موسى', 'لوط'], ['Nuh', 'Hud', 'Musa', 'Lut'],
     [Qr(71, 26, 'وقال نوح رب لا تذر علي الارض')]),
    ('prophets', 1, 'إلى أي قوم أُرسل هود عليه السلام؟', 'To which people was Hud sent?',
     ['عاد', 'ثمود', 'مدين', 'قوم تبع'], ["'Ad", 'Thamud', 'Madyan', "The people of Tubba'"],
     [Qr(7, 65, 'والي عاد اخاهم هودا')]),
    ('prophets', 1, 'إلى أي قوم أُرسل صالح عليه السلام؟', 'To which people was Salih sent?',
     ['ثمود', 'عاد', 'مدين', 'قوم لوط'], ['Thamud', "'Ad", 'Madyan', 'The people of Lut'],
     [Qr(7, 73, 'والي ثمود اخاهم صلحا')]),
    ('prophets', 1, 'ما آية صالح عليه السلام لقومه؟', 'What was the sign given to Salih for his people?',
     ['الناقة', 'العصا', 'السفينة', 'الحوت'], ['The she-camel', 'The staff', 'The ark', 'The whale'],
     [Qr(7, 73, 'هذه ناقه الله لكم ايه')]),
    ('prophets', 2, 'أي قوم كانوا ينحتون من الجبال بيوتًا؟', 'Which people carved homes out of the mountains?',
     ['ثمود', 'عاد', 'مدين', 'أهل سبأ'], ['Thamud', "'Ad", 'Madyan', 'The people of Saba'],
     [Qr(7, 74, 'وتنحتون الجبال بيوتا')]),
    ('prophets', 1, 'إلى أي قوم أُرسل شعيب عليه السلام؟', "To which people was Shu'ayb sent?",
     ['مدين', 'عاد', 'ثمود', 'سبأ'], ['Madyan', "'Ad", 'Thamud', 'Saba'],
     [Qr(7, 85, 'والي مدين اخاهم شعيبا')]),
    ('prophets', 2, 'أي نبي أمر قومه بإيفاء الكيل والميزان؟', 'Which prophet commanded his people to give full measure and weight?',
     ['شعيب', 'صالح', 'هود', 'يونس'], ["Shu'ayb", 'Salih', 'Hud', 'Yunus'],
     [Qr(7, 85, 'فاوفوا الكيل والميزان')]),
    ('prophets', 1, 'أي نبي اتخذه الله خليلًا؟', 'Which prophet did Allah take as an intimate friend (khalil)?',
     ['إبراهيم', 'موسى', 'نوح', 'عيسى'], ['Ibrahim', 'Musa', 'Nuh', "'Isa"],
     [Qr(4, 125, 'واتخذ الله ابرهيم خليلا')]),
    ('prophets', 1, 'أي نبي أُلقي في النار فكانت بردًا وسلامًا عليه؟', 'Which prophet was thrown into the fire which became cool and safe for him?',
     ['إبراهيم', 'لوط', 'إسماعيل', 'يوسف'], ['Ibrahim', 'Lut', "Isma'il", 'Yusuf'],
     [Qr(21, 69, 'كوني بردا وسلما علي ابرهيم')]),
    ('prophets', 1, 'من الذي شارك إبراهيم في رفع قواعد البيت؟', 'Who helped Ibrahim raise the foundations of the House (the Ka\'bah)?',
     ['إسماعيل', 'إسحاق', 'لوط', 'يعقوب'], ["Isma'il", 'Ishaq', 'Lut', "Ya'qub"],
     [Qr(2, 127, 'واذ يرفع ابرهم القواعد من البيت واسمعيل')]),
    ('prophets', 2, 'ما اسم أبي إبراهيم عليه السلام كما ورد في القرآن؟', "What is the name of Ibrahim's father as given in the Quran?",
     ['آزر', 'تارح', 'عمران', 'لامك'], ['Azar', 'Tarih', "'Imran", 'Lamech'],
     [Qr(6, 74, 'واذ قال ابرهيم لابيه ازر')]),
    ('prophets', 2, 'ماذا فعل إبراهيم عليه السلام بأصنام قومه؟', 'What did Ibrahim do to the idols of his people?',
     ['جعلها جذاذًا إلا كبيرًا لهم', 'أحرقها كلها', 'دفنها في الرمل', 'ألقاها في البحر'],
     ['Broke them into pieces except the biggest', 'Burned them all', 'Buried them in sand', 'Threw them into the sea'],
     [Qr(21, 58, 'فجعلهم جذذا الا كبيرا لهم')]),
    ('prophets', 2, 'بمَ فدى الله الذبيحَ ابنَ إبراهيم؟', "With what did Allah ransom Ibrahim's son who was to be sacrificed?",
     ['بذبح عظيم', 'بمال كثير', 'بناقة', 'بصلاة'], ['A great sacrifice', 'Great wealth', 'A she-camel', 'A prayer'],
     [Qr(37, 107, 'وفدينه بذبح عظيم')]),
    ('prophets', 2, 'أي نبي دعا: «رب اجعل هذا البلد آمنًا»؟', 'Which prophet prayed: "My Lord, make this city secure"?',
     ['إبراهيم', 'إسماعيل', 'محمد ﷺ', 'لوط'], ['Ibrahim', "Isma'il", 'Muhammad ﷺ', 'Lut'],
     [Qr(14, 35, 'واذ قال ابرهيم رب اجعل هذا البلد امنا')]),
    ('prophets', 2, 'بمَ أكرم إبراهيم ضيوفه من الملائكة؟', 'What did Ibrahim serve to his angelic guests?',
     ['عجل حنيذ', 'تمر ولبن', 'خبز وعسل', 'سمك مشوي'], ['A roasted calf', 'Dates and milk', 'Bread and honey', 'Grilled fish'],
     [Qr(11, 69, 'فما لبث ان جا بعجل حنيذ')]),
    ('prophets', 2, 'من أُمر أن يؤذّن في الناس بالحج؟', 'Who was commanded to proclaim the Hajj to mankind?',
     ['إبراهيم', 'موسى', 'نوح', 'سليمان'], ['Ibrahim', 'Musa', 'Nuh', 'Sulayman'],
     [Qr(22, 26, 'واذ بوانا لابرهيم مكان البيت'), Qr(22, 27, 'واذن في الناس بالحج')]),
    ('prophets', 3, 'أي نبي وصفه القرآن بأنه «كان أمة»؟', 'Which prophet does the Quran describe as having been "a nation (ummah)"?',
     ['إبراهيم', 'نوح', 'موسى', 'هود'], ['Ibrahim', 'Nuh', 'Musa', 'Hud'],
     [Qr(16, 120, 'ان ابرهيم كان امه')]),
    ('prophets', 2, 'أي نبي بُشّرت امرأة إبراهيم بمولده ومن ورائه يعقوب؟', "Which prophet's birth was announced to Ibrahim's wife, with Ya'qub after him?",
     ['إسحاق', 'إسماعيل', 'لوط', 'يوسف'], ['Ishaq', "Isma'il", 'Lut', 'Yusuf'],
     [Qr(11, 71, 'فبشرنها باسحق ومن ورا اسحق يعقوب')]),
    ('prophets', 2, 'أي نبي آمن لإبراهيم وهاجر معه؟', 'Which prophet believed in Ibrahim and emigrated with him?',
     ['لوط', 'إسحاق', 'شعيب', 'هود'], ['Lut', 'Ishaq', "Shu'ayb", 'Hud'],
     [Qr(29, 26, 'فامن له لوط')]),
    ('prophets', 2, 'من التي كانت من الغابرين ولم تنجُ مع لوط عليه السلام؟', 'Who stayed behind and was not saved with Lut?',
     ['امرأته', 'ابنته', 'أمه', 'أخته'], ['His wife', 'His daughter', 'His mother', 'His sister'],
     [Qr(7, 83, 'فانجينه واهله الا امراته كانت من الغبرين')]),
    ('prophets', 1, 'أي نبي ألقاه إخوته في غيابة الجب؟', 'Which prophet was thrown into the depths of a well by his brothers?',
     ['يوسف', 'موسى', 'يونس', 'يحيى'], ['Yusuf', 'Musa', 'Yunus', 'Yahya'],
     [Qr(12, 15, 'في غيبت الجب')]),
    ('prophets', 2, 'بماذا جاء إخوة يوسف على قميصه؟', "What did Yusuf's brothers bring on his shirt?",
     ['بدم كذب', 'بتراب', 'بماء', 'بصوف الغنم'], ['False blood', 'Dust', 'Water', "Sheep's wool"],
     [Qr(12, 18, 'علي قميصه بدم كذب')]),
    ('prophets', 2, 'ماذا رأى الملك في منامه في قصة يوسف عليه السلام؟', 'What did the king see in his dream in the story of Yusuf?',
     ['سبع بقرات سمان يأكلهن سبع عجاف', 'أحد عشر كوكبًا', 'طيرًا يأكل من خبز', 'نارًا تحرق المدينة'],
     ['Seven fat cows eaten by seven lean ones', 'Eleven stars', 'Birds eating from bread', 'A fire burning the city'],
     [Qr(12, 43, 'اني اري سبع بقرت سمان')]),
    ('prophets', 2, 'أي نبي ابيضّت عيناه من الحزن على ابنه؟', 'Which prophet lost his sight from grief for his son?',
     ['يعقوب', 'إبراهيم', 'نوح', 'زكريا'], ["Ya'qub", 'Ibrahim', 'Nuh', 'Zakariyya'],
     [Qr(12, 84, 'وابيضت عيناه من الحزن')]),
    ('prophets', 2, 'بمَ ارتدّ يعقوب عليه السلام بصيرًا؟', "What restored Ya'qub's sight?",
     ['قميص يوسف أُلقي على وجهه', 'ماء زمزم', 'دواء من الأعشاب', 'مسح جبريل'],
     ["Yusuf's shirt cast over his face", 'Zamzam water', 'An herbal medicine', "Jibril's touch"],
     [Qr(12, 93, 'اذهبوا بقميصي هذا فالقوه علي وجه ابي')]),
    ('prophets', 2, 'ماذا طلب يوسف عليه السلام أن يُجعل عليه؟', 'What did Yusuf ask to be put in charge of?',
     ['خزائن الأرض', 'جيش الملك', 'بناء القصور', 'السجن'], ['The storehouses of the land', "The king's army", 'Building palaces', 'The prison'],
     [Qr(12, 55, 'اجعلني علي خزاين الارض')]),
    ('prophets', 2, 'أي نبي قال: «رب السجن أحب إلي مما يدعونني إليه»؟', 'Which prophet said: "My Lord, prison is dearer to me than what they invite me to"?',
     ['يوسف', 'موسى', 'يونس', 'إبراهيم'], ['Yusuf', 'Musa', 'Yunus', 'Ibrahim'],
     [Qr(12, 33, 'رب السجن احب الي مما يدعونني اليه')]),
    ('prophets', 2, 'أي نبي علّمه الله تأويل الأحاديث (الرؤى)؟', 'Which prophet did Allah teach the interpretation of dreams?',
     ['يوسف', 'سليمان', 'داود', 'إسحاق'], ['Yusuf', 'Sulayman', 'Dawud', 'Ishaq'],
     [Qr(12, 6, 'ويعلمك من تاويل الاحاديث')]),
    ('prophets', 1, 'أين أُلقي موسى عليه السلام وهو رضيع؟', 'Where was Musa placed as a baby?',
     ['في اليمّ داخل تابوت', 'في بئر', 'في كهف', 'في سوق المدينة'], ['In the river, inside a chest', 'In a well', 'In a cave', 'In the city market'],
     [Qr(20, 39, 'ان اقذفيه في التابوت فاقذفيه في اليم')]),
    ('prophets', 2, 'من قالت عن موسى الرضيع: «قرّت عين لي ولك»؟', 'Who said of baby Musa: "A comfort of the eye for me and for you"?',
     ['امرأة فرعون', 'أم موسى', 'أخت موسى', 'بنت شعيب'], ["Pharaoh's wife", "Musa's mother", "Musa's sister", "Shu'ayb's daughter"],
     [Qr(28, 9, 'وقالت امرات فرعون قرت عين لي ولك')]),
    ('prophets', 2, 'من التي تتبّعت أثر موسى الرضيع بأمر أمه؟', "Who followed the chest of baby Musa at his mother's request?",
     ['أخته', 'خالته', 'امرأة فرعون', 'جارتها'], ['His sister', 'His aunt', "Pharaoh's wife", 'A neighbour'],
     [Qr(28, 11, 'وقالت لاخته قصيه')]),
    ('prophets', 1, 'إلامَ تحوّلت عصا موسى حين ألقاها؟', "What did Musa's staff become when he threw it down?",
     ['حية تسعى', 'شجرة', 'طائر', 'نهر'], ['A moving snake', 'A tree', 'A bird', 'A river'],
     [Qr(20, 20, 'فاذا هي حيه تسعي')]),
    ('prophets', 2, 'ما آية موسى الثانية مع العصا؟', "What was Musa's second sign besides the staff?",
     ['يده تخرج بيضاء من غير سوء', 'نار لا تحرقه', 'كلامه في المهد', 'ناقة من الصخر'],
     ['His hand coming out white without harm', 'Fire that did not burn him', 'Speaking in the cradle', 'A she-camel from the rock'],
     [Qr(20, 22, 'تخرج بيضا من غير سو')]),
    ('prophets', 1, 'من طلب موسى عليه السلام أن يكون وزيرًا له؟', 'Whom did Musa ask to be his helper (wazir)?',
     ['هارون أخاه', 'يوشع', 'شعيب', 'الخضر'], ['His brother Harun', "Yusha'", "Shu'ayb", 'Al-Khidr'],
     [Qr(20, 30, 'هرون اخي')]),
    ('prophets', 2, 'في أي وادٍ نودي موسى عليه السلام؟', 'In which valley was Musa called by his Lord?',
     ['الوادي المقدس طوى', 'وادي النمل', 'وادي القرى', 'وادي العقيق'], ['The sacred valley of Tuwa', 'The valley of the ants', 'Wadi al-Qura', "Wadi al-'Aqiq"],
     [Qr(20, 12, 'انك بالواد المقدس طوي')]),
    ('prophets', 2, 'إلى أي بلد توجّه موسى بعد خروجه من مصر خائفًا؟', 'Where did Musa head after leaving Egypt in fear?',
     ['مدين', 'فلسطين', 'اليمن', 'الحجاز'], ['Madyan', 'Palestine', 'Yemen', 'Hijaz'],
     [Qr(28, 22, 'ولما توجه تلقا مدين')]),
    ('prophets', 2, 'من الذي قال: «أنا ربكم الأعلى»؟', 'Who said: "I am your lord, the most high"?',
     ['فرعون', 'النمرود', 'قارون', 'هامان'], ['Pharaoh', 'Nimrod', 'Qarun', 'Haman'],
     [Qr(79, 24, 'فقال انا ربكم الاعلي')]),
    ('prophets', 1, 'كيف كانت نهاية فرعون؟', "How did Pharaoh's end come?",
     ['غرق في البحر', 'خُسفت به الأرض', 'أصابته صاعقة', 'مات في قصره'], ['He drowned in the sea', 'The earth swallowed him', 'A thunderbolt struck him', 'He died in his palace'],
     [Qr(10, 90, 'حتي اذا ادركه الغرق')]),
    ('prophets', 3, 'من الذي خُسفت به وبداره الأرض لكِبره بماله؟', 'Who was swallowed by the earth, with his house, for his arrogance about his wealth?',
     ['قارون', 'فرعون', 'هامان', 'السامري'], ['Qarun', 'Pharaoh', 'Haman', 'As-Samiri'],
     [Qr(28, 81, 'فخسفنا به وبداره الارض')]),
    ('prophets', 1, 'ماذا حدث حين ضرب موسى البحر بعصاه؟', 'What happened when Musa struck the sea with his staff?',
     ['انفلق البحر', 'تجمد الماء', 'خرجت منه سفينة', 'جفّ في لحظته كله'],
     ['The sea split apart', 'The water froze', 'A ship came out of it', 'It all dried up instantly'],
     [Qr(26, 63, 'ان اضرب بعصاك البحر فانفلق')]),
    ('prophets', 2, 'أي هذه كان من الآيات التي أُرسلت على قوم فرعون؟', "Which of these was among the signs sent upon Pharaoh's people?",
     ['الضفادع', 'الثلج', 'الذئاب', 'البرد القارس'], ['Frogs', 'Snow', 'Wolves', 'Bitter cold'],
     [Qr(7, 133, 'والضفادع')]),
    ('prophets', 2, 'من الذي صنع العجل لبني إسرائيل؟', 'Who made the calf for the Children of Israel?',
     ['السامري', 'هارون', 'قارون', 'هامان'], ['As-Samiri', 'Harun', 'Qarun', 'Haman'],
     [Qr(20, 85, 'واضلهم السامري')]),
    ('prophets', 1, 'أي نبي كلّمه الله تكليمًا؟', 'To which prophet did Allah speak directly?',
     ['موسى', 'نوح', 'إبراهيم', 'عيسى'], ['Musa', 'Nuh', 'Ibrahim', "'Isa"],
     [Qr(4, 164, 'وكلم الله موسي تكليما')]),
    ('prophets', 3, 'ماذا صنع العبد الصالح بالسفينة في قصته مع موسى؟', 'What did the righteous servant do to the boat in his story with Musa?',
     ['خرقها', 'أحرقها', 'باعها', 'ربطها بالشاطئ'], ['Made a hole in it', 'Burned it', 'Sold it', 'Tied it to the shore'],
     [Qr(18, 71, 'حتي اذا ركبا في السفينه خرقها')]),
    ('prophets', 3, 'ماذا أقام العبد الصالح في القرية التي أبى أهلها أن يضيفوهما؟', 'What did the righteous servant set up in the town whose people refused them hospitality?',
     ['جدارًا يريد أن ينقضّ', 'بئرًا', 'مسجدًا', 'سوقًا'], ['A wall about to collapse', 'A well', 'A mosque', 'A market'],
     [Qr(18, 77, 'فوجدا فيها جدارا يريد ان ينقض فاقامه')]),
    ('prophets', 1, 'أي نبي التقمه الحوت؟', 'Which prophet was swallowed by the whale?',
     ['يونس', 'نوح', 'موسى', 'أيوب'], ['Yunus', 'Nuh', 'Musa', 'Ayyub'],
     [Qr(37, 139, 'وان يونس لمن المرسلين'), Qr(37, 142, 'فالتقمه الحوت')]),
    ('prophets', 2, 'بمَ لُقّب يونس عليه السلام في القرآن الكريم؟', 'By what title is Yunus called in the Quran?',
     ['ذو النون', 'ذو الكفل', 'ذو القرنين', 'الخليل'], ['Dhun-Nun (the one of the fish)', 'Dhul-Kifl', 'Dhul-Qarnayn', 'Al-Khalil'],
     [Qr(21, 87, 'وذا النون')]),
    ('prophets', 2, 'ماذا نادى يونس عليه السلام في الظلمات؟', 'What did Yunus call out in the darkness?',
     ['لا إله إلا أنت سبحانك إني كنت من الظالمين', 'رب إني مسني الضر', 'رب هب لي من لدنك ذرية طيبة', 'رب نجني من القوم الظالمين'],
     ['"There is no god but You, glory be to You; I was among the wrongdoers"', '"My Lord, harm has touched me"',
      '"My Lord, grant me good offspring"', '"My Lord, save me from the wrongdoing people"'],
     [Qr(21, 87, 'لا اله الا انت سبحنك اني كنت من الظلمين')]),
    ('prophets', 3, 'إلى كم من الناس أُرسل يونس عليه السلام؟', 'To how many people was Yunus sent?',
     ['مئة ألف أو يزيدون', 'عشرة آلاف', 'ألف رجل', 'سبعين ألفًا'], ['A hundred thousand or more', 'Ten thousand', 'A thousand men', 'Seventy thousand'],
     [Qr(37, 147, 'وارسلنه الي مايه الف او يزيدون')]),
    ('prophets', 1, 'أي نبي يُضرب به المثل في الصبر على البلاء؟', 'Which prophet is the example of patience in affliction?',
     ['أيوب', 'يوسف', 'يونس', 'داود'], ['Ayyub', 'Yusuf', 'Yunus', 'Dawud'],
     [Qr(21, 83, 'وايوب اذ نادي ربه اني مسني الضر'), Qr(38, 44, 'انا وجدنه صابرا')]),
    ('prophets', 1, 'أي كتاب آتاه الله داود عليه السلام؟', 'Which scripture did Allah give to Dawud?',
     ['الزبور', 'التوراة', 'الإنجيل', 'الصحف'], ['The Zabur (Psalms)', 'The Tawrah', 'The Injil', 'The Scrolls'],
     [Qr(4, 163, 'واتينا داود زبورا')]),
    ('prophets', 1, 'أي معدن ألانه الله لداود عليه السلام؟', 'Which metal did Allah make soft for Dawud?',
     ['الحديد', 'الذهب', 'النحاس', 'الفضة'], ['Iron', 'Gold', 'Copper', 'Silver'],
     [Qr(34, 10, 'والنا له الحديد')]),
    ('prophets', 2, 'من الذي قتله داود عليه السلام في جيش طالوت؟', "Whom did Dawud slay in Talut's army?",
     ['جالوت', 'فرعون', 'النمرود', 'قارون'], ['Jalut (Goliath)', 'Pharaoh', 'Nimrod', 'Qarun'],
     [Qr(2, 251, 'وقتل داود جالوت')]),
    ('prophets', 2, 'مِن كسب مَن كان يأكل نبي الله داود عليه السلام؟', 'From whose earnings did the prophet Dawud eat?',
     ['من عمل يده', 'من بيت المال', 'من الغنائم', 'من هدايا الناس'], ['From the work of his own hands', 'From the treasury', 'From the spoils of war', "From people's gifts"],
     [Hd('bukhari', 2072, 'كان ياكل من عمل يده')]),
    ('prophets', 2, 'كيف كان صيام داود عليه السلام الذي وُصف بأنه أحب الصيام إلى الله؟', 'How did Dawud fast, the fasting described as most beloved to Allah?',
     ['يصوم يومًا ويفطر يومًا', 'يصوم الدهر كله', 'يصوم الاثنين فقط', 'يصوم ثلاثة أيام في السنة'],
     ['Fasting one day and not the next', 'Fasting every day', 'Fasting only on Mondays', 'Fasting three days a year'],
     [Hd('bukhari', 1131, 'احب الصيام الي الله صيام داود'), Hd('bukhari', 1131, 'ويصوم يوما ويفطر يوما')]),
    ('prophets', 1, 'ماذا سخّر الله لسليمان عليه السلام؟', 'What did Allah subject to Sulayman?',
     ['الريح', 'البحر', 'الشمس', 'البراكين'], ['The wind', 'The sea', 'The sun', 'The volcanoes'],
     [Qr(34, 12, 'ولسليمن الريح')]),
    ('prophets', 1, 'أي طائر جاء سليمان بنبأ من سبأ؟', 'Which bird brought Sulayman news from Saba?',
     ['الهدهد', 'الغراب', 'الحمامة', 'الصقر'], ['The hoopoe', 'The crow', 'The dove', 'The falcon'],
     [Qr(27, 20, 'الهدهد'), Qr(27, 22, 'وجيتك من سبا بنبا يقين')]),
    ('prophets', 2, 'ممّ تبسّم سليمان عليه السلام ضاحكًا؟', 'What made Sulayman smile and laugh?',
     ['من قول النملة', 'من فعل الهدهد', 'من جواب الملكة', 'من لعب الجن'], ['The words of an ant', "The hoopoe's deed", "The queen's reply", 'The play of the jinn'],
     [Qr(27, 19, 'فتبسم ضاحكا من قولها')]),
    ('prophets', 3, 'من الذي أحضر عرش الملكة قبل أن يرتدّ طرف سليمان؟', "Who brought the queen's throne before Sulayman's glance returned to him?",
     ['الذي عنده علم من الكتاب', 'عفريت من الجن', 'الهدهد', 'جنود سليمان من الإنس'],
     ['The one who had knowledge of the Book', "An 'ifrit of the jinn", 'The hoopoe', "Sulayman's human soldiers"],
     [Qr(27, 40, 'قال الذي عنده علم من الكتب انا اتيك به قبل ان يرتد اليك طرفك')]),
    ('prophets', 3, 'ما الذي دلّ الجن على موت سليمان عليه السلام؟', 'What showed the jinn that Sulayman had died?',
     ['دابة الأرض تأكل منسأته', 'صوت من السماء', 'سقوط عرشه', 'نداء الهدهد'],
     ['A creature of the earth eating his staff', 'A voice from the sky', 'His throne falling', "The hoopoe's call"],
     [Qr(34, 14, 'دابه الارض تاكل منساته')]),
    ('prophets', 1, 'من الذي كفل مريم عليها السلام؟', 'Who took charge of Maryam?',
     ['زكريا', 'عمران', 'يحيى', 'يوسف النجار'], ['Zakariyya', "'Imran", 'Yahya', 'Joseph the carpenter'],
     [Qr(3, 37, 'وكفلها زكريا')]),
    ('prophets', 2, 'ماذا كان زكريا يجد عند مريم كلما دخل عليها المحراب؟', 'What did Zakariyya find with Maryam whenever he entered her prayer niche?',
     ['رزقًا', 'كتبًا', 'ملائكة', 'ذهبًا'], ['Provision (food)', 'Books', 'Angels', 'Gold'],
     [Qr(3, 37, 'كلما دخل عليها زكريا المحراب وجد عندها رزقا')]),
    ('prophets', 1, 'بأي غلام بُشّر زكريا عليه السلام؟', 'Of which son was Zakariyya given glad tidings?',
     ['يحيى', 'عيسى', 'إسحاق', 'إسماعيل'], ['Yahya', "'Isa", 'Ishaq', "Isma'il"],
     [Qr(19, 7, 'اسمه يحيي')]),
    ('prophets', 3, 'كم ليلة جُعلت آية لزكريا ألا يكلّم الناس؟', "For how many nights was Zakariyya's sign that he would not speak to people?",
     ['ثلاث ليال', 'سبع ليال', 'ليلة واحدة', 'عشر ليال'], ['Three nights', 'Seven nights', 'One night', 'Ten nights'],
     [Qr(19, 10, 'الا تكلم الناس ثلث ليال سويا')]),
    ('prophets', 2, 'ما الحرفة التي كان عليها زكريا عليه السلام؟', 'What was the trade of Zakariyya?',
     ['النجارة', 'الحدادة', 'التجارة', 'الرعي'], ['Carpentry', 'Blacksmithing', 'Trade', 'Shepherding'],
     [Hd('muslim', 2379, 'كان زكرياء نجارا')]),
    ('prophets', 2, 'أي نبي آتاه الله الحكم صبيًّا؟', 'Which prophet was given wisdom (judgement) as a child?',
     ['يحيى', 'سليمان', 'يوسف', 'إسحاق'], ['Yahya', 'Sulayman', 'Yusuf', 'Ishaq'],
     [Qr(19, 12, 'ييحيي خذ الكتب بقوه واتينه الحكم صبيا')]),
    ('prophets', 1, 'أي نبي كلّم الناس في المهد؟', 'Which prophet spoke to people from the cradle?',
     ['عيسى', 'يحيى', 'موسى', 'سليمان'], ["'Isa", 'Yahya', 'Musa', 'Sulayman'],
     [Qr(19, 29, 'كيف نكلم من كان في المهد صبيا')]),
    ('prophets', 1, 'ما أول ما قاله عيسى عليه السلام في المهد؟', "What were 'Isa's first words from the cradle?",
     ['إني عبد الله', 'أنا ابن مريم', 'السلام عليكم', 'لا إله إلا الله'], ['"I am the servant of Allah"', '"I am the son of Maryam"', '"Peace be upon you"', '"There is no god but Allah"'],
     [Qr(19, 30, 'قال اني عبد الله')]),
    ('prophets', 1, 'من أم عيسى عليه السلام؟', "Who is the mother of 'Isa?",
     ['مريم', 'آسية', 'حنة', 'سارة'], ['Maryam', 'Asiya', 'Hannah', 'Sarah'],
     [Qr(19, 34, 'ذلك عيسي ابن مريم')]),
    ('prophets', 2, 'بمَ أُمرت مريم أن تهزّ إليها؟', 'What was Maryam told to shake towards her?',
     ['جذع النخلة', 'غصن الزيتون', 'شجرة التين', 'عنقود العنب'], ['The trunk of the palm tree', 'An olive branch', 'A fig tree', 'A bunch of grapes'],
     [Qr(19, 25, 'وهزي اليك بجذع النخله')]),
    ('prophets', 2, 'ماذا كان عيسى عليه السلام يخلق من الطين بإذن الله؟', "What did 'Isa fashion from clay by Allah's permission?",
     ['كهيئة الطير', 'كهيئة الإنسان', 'أواني للطعام', 'بيوتًا'], ['The shape of a bird', 'The shape of a man', 'Vessels for food', 'Houses'],
     [Qr(3, 49, 'اني اخلق لكم من الطين كهيه الطير')]),
    ('prophets', 2, 'من الذين كانوا يُسمَّون الحواريين؟', 'Who were called the Hawariyyun (disciples)?',
     ['أنصار عيسى عليه السلام', 'أصحاب موسى', 'أصحاب الكهف', 'أهل مدين'], ["The helpers of 'Isa", 'The companions of Musa', 'The People of the Cave', 'The people of Madyan'],
     [Qr(3, 52, 'قال الحواريون نحن انصار الله')]),
    ('prophets', 2, 'من الذين سألوا عيسى أن تنزل عليهم مائدة من السماء؟', "Who asked 'Isa for a table spread to be sent down from the sky?",
     ['الحواريون', 'بنو إسرائيل في التيه', 'قوم صالح', 'أهل مكة'], ['The disciples', 'The Israelites in the wilderness', 'The people of Salih', 'The people of Makkah'],
     [Qr(5, 112, 'اذ قال الحواريون'), Qr(5, 112, 'مايده من السما')]),
    ('prophets', 1, 'أي كتاب آتاه الله عيسى عليه السلام؟', "Which scripture did Allah give to 'Isa?",
     ['الإنجيل', 'التوراة', 'الزبور', 'القرآن'], ['The Injil (Gospel)', 'The Tawrah', 'The Zabur', 'The Quran'],
     [Qr(5, 46, 'بعيسي ابن مريم'), Qr(5, 46, 'واتينه الانجيل')]),
    ('prophets', 2, 'ماذا يقرر القرآن الكريم عن نهاية عيسى عليه السلام في الدنيا؟', "What does the Quran state about the end of 'Isa's time on earth?",
     ['رفعه الله إليه', 'صُلب ومات', 'مات بمرض', 'غرق في البحر'], ['Allah raised him to Himself', 'He was crucified and died', 'He died of illness', 'He drowned'],
     [Qr(4, 157, 'وما قتلوه وما صلبوه'), Qr(4, 158, 'بل رفعه الله اليه')]),
    ('prophets', 2, 'صحف أي نبيين ذُكرت في آخر سورة الأعلى؟', "The scrolls of which two prophets are mentioned at the end of Surah Al-A'la?",
     ['إبراهيم وموسى', 'نوح وهود', 'داود وسليمان', 'عيسى ويحيى'], ['Ibrahim and Musa', 'Nuh and Hud', 'Dawud and Sulayman', "'Isa and Yahya"],
     [Qr(87, 19, 'صحف ابرهيم وموسي')]),
    ('prophets', 2, 'أي نبي وصفه القرآن بأنه كان صدّيقًا نبيًّا ورفعه مكانًا عليًّا؟', 'Which prophet does the Quran describe as truthful and raised to a high station?',
     ['إدريس', 'إلياس', 'اليسع', 'لوط'], ['Idris', 'Ilyas', "Al-Yasa'", 'Lut'],
     [Qr(19, 56, 'ادريس انه كان صديقا نبيا'), Qr(19, 57, 'ورفعنه مكانا عليا')]),
    ('prophets', 3, 'مع مَن ذُكر ذو الكفل في سورة الأنبياء؟', "With whom is Dhul-Kifl mentioned in Surah Al-Anbiya?",
     ['إسماعيل وإدريس', 'موسى وهارون', 'نوح وهود', 'يحيى وعيسى'], ["Isma'il and Idris", 'Musa and Harun', 'Nuh and Hud', "Yahya and 'Isa"],
     [Qr(21, 85, 'واسمعيل وادريس وذا الكفل')]),
    ('prophets', 3, 'أي نبي كان قومه يعبدون صنمًا يُسمّى «بعلًا»؟', "Which prophet's people worshipped an idol called Ba'l?",
     ['إلياس', 'هود', 'صالح', 'شعيب'], ['Ilyas', 'Hud', 'Salih', "Shu'ayb"],
     [Qr(37, 123, 'وان الياس لمن المرسلين'), Qr(37, 125, 'اتدعون بعلا')]),
    ('prophets', 3, 'في أي سورة ورد ذكر النبي اليسع مع إسماعيل ويونس ولوط؟', "In which surah is Al-Yasa' mentioned alongside Isma'il, Yunus and Lut?",
     ['الأنعام', 'البقرة', 'يس', 'الكهف'], ["Al-An'am", 'Al-Baqarah', 'Ya-Sin', 'Al-Kahf'],
     [Qr(6, 86, 'واسمعيل واليسع ويونس ولوطا')]),
    ('prophets', 2, 'أي امرأتين ضربهما الله مثلًا للذين كفروا؟', 'Which two women does Allah give as an example for those who disbelieve?',
     ['امرأة نوح وامرأة لوط', 'امرأة فرعون ومريم', 'امرأة العزيز وأم موسى', 'بلقيس وأخت موسى'],
     ['The wives of Nuh and Lut', "Pharaoh's wife and Maryam", "The Aziz's wife and Musa's mother", "The queen of Saba and Musa's sister"],
     [Qr(66, 10, 'امرات نوح وامرات لوط')]),
    ('prophets', 2, 'من المرأة التي ضربها الله مثلًا للذين آمنوا مع مريم؟', 'Which woman, along with Maryam, is given as an example for the believers?',
     ['امرأة فرعون', 'امرأة نوح', 'امرأة لوط', 'امرأة العزيز'], ["Pharaoh's wife", "Nuh's wife", "Lut's wife", "The Aziz's wife"],
     [Qr(66, 11, 'امرات فرعون')]),
    ('prophets', 2, 'ما العمل الذي قال النبي ﷺ إنه ما من نبي إلا وقد عمله؟', 'Which work did the Prophet ﷺ say every prophet had done?',
     ['رعي الغنم', 'التجارة', 'الزراعة', 'النجارة'], ['Herding sheep', 'Trade', 'Farming', 'Carpentry'],
     [Hd('bukhari', 2262, 'ما بعث الله نبيا الا رعي الغنم')]),
    ('prophets', 3, 'من أول الرسل إلى أهل الأرض كما في حديث الشفاعة؟', 'Who is the first messenger to the people of the earth according to the hadith of intercession?',
     ['نوح', 'آدم', 'إدريس', 'إبراهيم'], ['Nuh', 'Adam', 'Idris', 'Ibrahim'],
     [Hd('bukhari', 4712, 'انت اول الرسل الي اهل الارض')]),
    ('prophets', 3, 'من أول من يُكسى يوم القيامة؟', 'Who is the first to be clothed on the Day of Resurrection?',
     ['إبراهيم', 'موسى', 'عيسى', 'آدم'], ['Ibrahim', 'Musa', "'Isa", 'Adam'],
     [Hd('bukhari', 3349, 'واول من يكسي يوم القيامه ابراهيم')]),
    ('prophets', 2, 'أي نبي قال لأبيه: «يا أبت إني رأيت أحد عشر كوكبًا»؟', 'Which prophet told his father: "O my father, I saw eleven stars"?',
     ['يوسف', 'إسماعيل', 'إسحاق', 'موسى'], ['Yusuf', "Isma'il", 'Ishaq', 'Musa'],
     [Qr(12, 4, 'اذ قال يوسف لابيه يابت اني رايت احد عشر كوكبا')]),
    ('prophets', 2, 'من الملكة التي أسلمت مع سليمان لله رب العالمين؟', 'Which queen submitted, with Sulayman, to Allah the Lord of the worlds?',
     ['ملكة سبأ', 'ملكة مصر', 'ملكة الروم', 'ملكة الفرس'], ['The queen of Saba', 'The queen of Egypt', 'The queen of Rome', 'The queen of Persia'],
     [Qr(27, 44, 'واسلمت مع سليمن لله رب العلمين')]),
    ('prophets', 3, 'أي نبي قال لقومه: «أتبنون بكل ريع آية تعبثون»؟', 'Which prophet asked his people: "Do you build a landmark on every height, amusing yourselves?"',
     ['هود', 'صالح', 'شعيب', 'لوط'], ['Hud', 'Salih', "Shu'ayb", 'Lut'],
     [Qr(26, 124, 'اذ قال لهم اخوهم هود'), Qr(26, 128, 'اتبنون بكل ريع ايه تعبثون')]),
    ('prophets', 2, 'من الذي قال عنه القرآن: «واذكر في الكتاب إسماعيل إنه كان صادق الوعد»؟', 'Whom does the Quran describe as "true to his promise"?',
     ['إسماعيل', 'إسحاق', 'يعقوب', 'يوسف'], ["Isma'il", 'Ishaq', "Ya'qub", 'Yusuf'],
     [Qr(19, 54, 'واذكر في الكتب اسمعيل انه كان صادق الوعد')]),
    ('prophets', 3, 'بمَ وصف القرآن الكريم إبراهيم عليه السلام في سورة هود؟', 'How does Surah Hud describe Ibrahim?',
     ['لحليم أواه منيب', 'شديد البطش', 'كثير المال', 'ملك عظيم'], ['Forbearing, tender-hearted, oft-returning', 'Mighty in assault', 'Very wealthy', 'A great king'],
     [Qr(11, 75, 'ان ابرهيم لحليم اوه منيب')]),
    ('prophets', 1, 'من خاتم الأنبياء والمرسلين؟', 'Who is the seal of the prophets and messengers?',
     ['محمد ﷺ', 'عيسى', 'موسى', 'إبراهيم'], ['Muhammad ﷺ', "'Isa", 'Musa', 'Ibrahim'],
     [Qr(33, 40, 'ولكن رسول الله وخاتم النبين')]),
]
